### ISSUE TITLE
command preview is not indented

### ISSUE THREAD

**Issue by tarekrached** [stitchfix/flotilla-os#103]
this code in the command:
```
if [ -e "${REQS_PATH}" ]; then
  pip install -r "${REQS_PATH}"
fi
```
shows up without indentation like so:
![image](https://user-images.githubusercontent.com/167218/52153459-f60e6380-262e-11e9-9589-a3b20f15a51a.png)

**Comment by psunnn** [comment]
@tarekrached is this still an issue? If not, please close, thanks!
