### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by 2morales** [stitchfix/flotilla-os#106]
I have been trying to setup flotilla-os in my personal computer, in order to explore and understand how this project works. It seems very nice to have a"self-service framework that dramatically simplifies the process of defining and executing containerized jobs".

### I did the following:

- I followed the documentation and got the UI working
- I have also checked in my localhost portainer if there was something I was missing

### The problem:
- the image from the repository "flotilla-os_flotilla" starts a container normally, then it crashes as soon as:
    1. flotilla ui starts, followed by a network error (link to image: https://imgur.com/cEqauy6)
    - OR
    1. the container starts, 10 seconds pass and it crashes

Last 50 lines of logs:

``` message="Initializing logs client" client=awslogs,
NoCredentialProviders: no valid providers in chain. Deprecated.,
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors,
problem describing log groups with prefix [flotilla-os-logs],
github.com/stitchfix/flotilla-os/clients/logs.(*CloudWatchLogsClient).namespaceExists,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/cloudwatch_logs_client.go:171,
github.com/stitchfix/flotilla-os/clients/logs.(*CloudWatchLogsClient).createNamespaceIfNotExists,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/cloudwatch_logs_client.go:155,
github.com/stitchfix/flotilla-os/clients/logs.(*CloudWatchLogsClient).Initialize,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/cloudwatch_logs_client.go:94,
github.com/stitchfix/flotilla-os/clients/logs.NewLogsClient,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/logs.go:34,,
n,
	/go/src/github.com/stitchfix/flotilla-os/main.go:77,
runtime.main,
	/usr/local/go/src/runtime/proc.go:200,
runtime.goexit,
	/usr/local/go/src/runtime/asm_amd64.s:1337,
problem checking if log namespace [flotilla-os-logs] exists,
github.com/stitchfix/flotilla-os/clients/logs.(*CloudWatchLogsClient).createNamespaceIfNotExists,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/cloudwatch_logs_client.go:157,
github.com/stitchfix/flotilla-os/clients/logs.(*CloudWatchLogsClient).Initialize,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/cloudwatch_logs_client.go:94,
github.com/stitchfix/flotilla-os/clients/logs.NewLogsClient,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/logs.go:34,,
n,
	/go/src/github.com/stitchfix/flotilla-os/main.go:77,
runtime.main,
	/usr/local/go/src/runtime/proc.go:200,
runtime.goexit,
	/usr/local/go/src/runtime/asm_amd64.s:1337,
problem initializing CloudWatchLogsClient,
github.com/stitchfix/flotilla-os/clients/logs.NewLogsClient,
	/go/src/github.com/stitchfix/flotilla-os/clients/logs/logs.go:35,,
n,
	/go/src/github.com/stitchfix/flotilla-os/main.go:77,
runtime.main,
	/usr/local/go/src/runtime/proc.go:200,
runtime.goexit,
	/usr/local/go/src/runtime/asm_amd64.s:1337,
unable to initialize logs client,,
n,
	/go/src/github.com/stitchfix/flotilla-os/main.go:79,
runtime.main,
	/usr/local/go/src/runtime/proc.go:200,
runtime.goexit,
	/usr/local/go/src/runtime/asm_amd64.s:1337,```


If anyone has faced or is facing the problem, I ask for your help.

Thank you in advance!

**Comment by 2morales** [comment]
### Notes: 
- I've been using the default ports for everything

**Comment by thedatachef** [comment]
@2morales the logs suggest missing AWS credentials. Did you set your AWS credentials in the env vars like the documentation suggests?  If you ran the commands in part 1. here (https://github.com/stitchfix/flotilla-os#minimal-assumptions) I'm curious if the values are empty. If so then there's likely an issue with your AWS configuration.

If the env vars are not set at all, then when you run `docker-compose up -d` you should get a warning like this.

```
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
```

**Comment by 2morales** [comment]
@thedatachef 

Hello,

My mistake, I didn't set my AWS credentials. Truth is I misinterpreted the obligation to use AWS credentials, and skipped the definition of them. I thought I could simply run locally and by not setting the credentials, I'd use my own machine for everything.

I did everything else in the right way, so I believe that if I set my credentials, flotilla will work as expected! I'll reply back to you whenever I try that again (in a few hours maybe, or tomorrow)

Since the problem are the credentials, is there any way of running flotilla on prem? 

Thank you for your reply.

**Comment by thedatachef** [comment]
There _currently_ is not, however that's a great issue that's also referenced by #82 

The interfaces support such a thing, but it's a fair amount of work.

**Comment by 2morales** [comment]
> There _currently_ is not, however that's a great issue that's also referenced by #82
> 
> The interfaces support such a thing, but it's a fair amount of work.

Okay! Feel free to close the issue since with the AWS credentials everything works fine.

Thank you!
