### ISSUE TITLE
Any plans for documentation?

### ISSUE THREAD

**Issue by ajbosco** [stitchfix/flotilla-os#19]
Wondering if this will be open sourced officially with documentation in the future?

**Comment by thedatachef** [comment]
Yes - currently it's an internal project written in python. We've been using it in production for over a year now. It's still in the process of being rewritten and moved over (see https://github.com/stitchfix/flotilla-os/blob/master/worker/status_worker.go, https://github.com/stitchfix/flotilla-os/blob/master/worker/reassign_worker.go) for open source. Once the move is finished (which also includes a UI component) look for an official release with documentation.
