### ISSUE TITLE
UI locks up when viewing logs

### ISSUE THREAD

**Issue by kzielnicki** [stitchfix/flotilla-os#250]
As of the last couple weeks, the flotilla UI has become very difficult to use for reading longer log files. Scrolling through logs will typically render a blank view which will take several seconds to fill in, and will sometimes lock up entirely.

Tagging @danfisher-sf who also reported noticing this.

**Comment by psunnn** [comment]
fixed in https://github.com/stitchfix/flotilla-os/pull/249
