### ISSUE TITLE
Fail on task creation if the group name is > 36 characters

### ISSUE THREAD

**Issue by stroxler** [stitchfix/flotilla-os#52]
At the moment flotilla allows tasks like this to be created, then fails to run them in an opaque way due to ECS errors. We shouldn't allow these tasks to be created in the first place, now that we know about the limit

**Comment by psunnn** [comment]
I'll add this as a validation step in the UI @stroxler

**Comment by patrickeganfoley** [comment]
Could we increase the limit too?
