### ISSUE TITLE
aa-ui-components no longer exists, and thus npm cannot install dependencies

### ISSUE THREAD

**Issue by brockf** [stitchfix/flotilla-os#93]
Hi all 👋 

It seems like the tool unfortunately cannot be installed anymore because the `aa-ui-components` repo no longer exists or is no longer public.

Install node dependencies errors out with:

```$ npm install
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/stitchfix/aa-ui-components.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128```

**Comment by psunnn** [comment]
@brockf Hi Brock! My apologizes, did not realize that this repo had been made private. I'll update the UI to include the components.

**Comment by psunnn** [comment]
@brockf this has been fixed.
